In [14]:
import numpy

In [18]:
vector = [1, 2, 3]

In [20]:
print(type(vector))

<class 'list'>


In [21]:
nvector = numpy.array(vector)

In [24]:
nvector.shape

(3,)

In [25]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [32]:
nmatrix = numpy.array(matrix)

In [33]:
nmatrix.shape

(3, 3)

In [34]:
j = 3
i = [1, 2, 3]
k = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
x = [
    [[1, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[5, 2, 3], [6, 2, 3], [8, 4, 2]],
    [[1, 7, 3], [6, 2, 3], [8, 4, 2]],
]

In [47]:
narr = numpy.array([1, 2, 3])
narr

array([1, 2, 3])

In [48]:
numpy.resize(narr, (4, 4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [50]:
narr.resize((3, 3), refcheck=False)

In [51]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
matrix = numpy.ones((5, 4))

In [53]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
matrix = numpy.zeros((4, 4))
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
numpy.diag(narr)

array([1, 0, 0])

In [56]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [59]:
m1 = numpy.ones((4, 5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [68]:
m2 = numpy.zeros((4, 3), int)
m2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
numpy.vstack([m1, m2])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [69]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0]])

In [76]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 5])


In [79]:
z = x * y
z

array([ 4, 10, 15])

In [80]:
x ** 2

array([1, 4, 9])

In [81]:
x.dot(y)

29

In [85]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [86]:
narr.T

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [87]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [88]:
narr.sum()

6

In [89]:
narr.max()

3

In [90]:
narr.min()

0

In [91]:
narr.argmax()

2

In [92]:
narr.argmin()

3

In [93]:
narr.mean()

0.6666666666666666

In [95]:
narr.std()

1.0540925533894598

In [100]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [101]:
mr[2]

4

In [102]:
mr[1:5]

array([ 1,  4,  9, 16])

In [106]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [107]:
mr[-2:]

array([169, 196])

In [110]:
mr[10::-2]

array([100,  64,  36,  16])

In [111]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [115]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [117]:
narr[::2, -1]

array([3, 0])

In [118]:
narr[narr >= 2]

array([2, 3])

In [119]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [120]:
marr = narr[-1]
marr

array([0, 0, 0])

In [123]:
marr[:] = 1
marr

array([1, 1, 1])

In [124]:
marr[:2] = 2
marr

array([2, 2, 1])

In [125]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [127]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [129]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [130]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [131]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[0, 2, 1],
       [6, 0, 9],
       [2, 8, 1],
       [2, 3, 1]])

In [136]:
for r in tarr:
    r = r ** 2
    print(r)

[0 4 1]
[36  0 81]
[ 4 64  1]
[4 9 1]


In [137]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is ', r)

index(0) is  [0 2 1]
index(1) is  [6 0 9]
index(2) is  [2 8 1]
index(3) is  [2 3 1]


In [138]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [139]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [141]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [142]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [143]:
len(arr) // 2

3

In [144]:
p = arr[len(arr) // 2]
p

9

In [145]:
l = [x for x in arr if x  < p]
l

[1, 4, 2, 8, 6, 3]

In [146]:
r = [x for x in arr if x > p]
r

[]

In [147]:
m = [x for x in arr if x == p]
m

[9]

In [148]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [149]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x  < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [150]:
h = [3, 6, 4, 1, 3, 9, 4]
quicksort(h)

[1, 3, 3, 4, 4, 6, 9]